sudo: required
language: java

services:
  - docker

before_install:
  - docker build -t alianza-dev/demo-travisci .

install: 
  - docker run alianza-dev/demo-travisci mvn install

after_install:
  - docker commit -m "After install of demo-travisci" alianza-dev/demo-travisci

script:
  - docker ps -a
